import { Inter } from "next/font/google";
import "./globals.scss";
import { Windowsize } from "@/data/componets/Windowsize";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-tw">
      <Windowsize>
        <body className={inter.className}>
          <main>{children}</main>
        </body>
      </Windowsize>
    </html>
  );
}
